### ISSUE TITLE
Package Podfile?

### ISSUE THREAD

**Issue by cmcewen** [BranchMetrics/React-Native-Deferred-Deep-Linking-SDK#11]
Hi! More just a question, but I was wondering if you had considered creating a package Podfile and having users install that as opposed to adding `pod 'Branch'` to the project Podfile. 

I created a library for iOS GCM, which depends on a Google pod and chose that approach (https://github.com/cmcewen/react-native-gcm-ios) based on the Facebook SDK (https://github.com/facebook/react-native-fbsdk), but just curious if you had any opinions on that front.

**Comment by rt2zz** [comment]
yes we support that mode, there is a podspec in the root of this project. You can use it as follows: https://github.com/BranchMetrics/React-Native-Deferred-Deep-Linking-SDK/blob/master/docs/installation.md#pod-only-installation 👍

**Comment by cmcewen** [comment]
😳
